### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by kkharji** [c4arl0s/Xcode#1]
Hey @c4arl0s, 

I found this to be extremely helpful and nice cheatsheet to take a look at so thank you ❤️ .

It would be nice if the images are in dark mode, 😆 I know it's not a really issue

**Comment by kkharji** [comment]
btw, I see you are using a number of represent as way to record notes, you may want to look at creating a single repo with wiki pages instead. Advantages:

- others can easily contribute if you allow it.
- no more broken links in readmes

**Comment by c4arl0s** [comment]
Hi!, Actually those broken links are broken because are private repos, are you interested in read those repos, tell me which ones do you like to read ! I could add you as a collaborator. By the other hand, I created several repos because sometimes one only repo is not able to render GIF files as I wishes. I have a few repos where I used dark mode, but sorry, not all them.

**Comment by kkharji** [comment]
@c4arl0s Oh I see that's cool, well I'd love to, I just briefly browse through them. I'm currently till the next week hopefully creating a developing package/plugin to be able to develop Xcode projects outside "Xcode" 😆 don't ask, I'm so much used to terminal that using Xcode and the mouse is extremely painful. btw if you like you can read more about my manual hack here https://github.com/tami5/playground/blob/master/swift/swiftui/notes/swiftui_with_nvim.md

**Comment by c4arl0s** [comment]
Ok, let me add you little by little to those repos. Oh! it sounds great, I love command line too.  I don't know yet SwiftUI but I promise to give it a look, as soon as I can. Let me add you to another repos tonight!

**Comment by kkharji** [comment]
Sounds great, great thanks @c4arl0s

**Comment by kkharji** [comment]
Yah SwiftUI, is what made really get into swift development, it's really amazing. I believe it the best way to develop user interfaces.

Declarative style of programming makes so much senses to me as opposed to imperative style, like you would have with UIKit or Builder patterns. Where you initialize a class then modify over time.

checkout https://www.youtube.com/c/Kavsoft, maybe follow a video along to the end to get a feel of SwiftUI.

**Comment by c4arl0s** [comment]
Oh great link, I am going to add you to my notes about SwiftUI, Actually a few months ago started to learn SwiftUI with Apple Course, you will see.

**Comment by kkharji** [comment]
@c4arl0s that would be great, I can start contributing to it if you like.

So far, I made few notes on practices and design for multiple devices

**Comment by c4arl0s** [comment]
Of course, I have been doing baby steps, but I think next year I will be using it in my job. I am going to make public the repo as well.
